<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A8JI6UM" failures="2" tests="2" name="Command line test" time="0.921" errors="0" timestamp="2021-10-01T18:03:02 COT">
  <testcase classname="test.TestGeneral" name="verificarCargaFundaciones" time="0.849">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at persistencia.FundacionesDAO.consultarFundaciones(FundacionesDAO.java:33)
at test.TestGeneral.verificarCargaFundaciones(TestGeneral.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- verificarCargaFundaciones -->
  <testcase classname="test.TestGeneral" name="verificarConexion" time="0.037">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.TestGeneral.verificarConexion(TestGeneral.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- verificarConexion -->
</testsuite> <!-- Command line test -->
